### ISSUE TITLE
Issue importing tiff in human rnascope

### ISSUE THREAD

**Issue by CynAro** [LieberInstitute/dotdotdot#10]
Hi,

I have an issue running the rnascope_human_tif function with my tif files. I have 4 channels and an overlay assigned as follows:
DAPI = 'CH1'; %
LIP = 'CH2';
DROP = 'Overlay';
addpath(genpath(toolbox)) %adding toolbox path to current working directory
rnascope_human_tif(filename, toolbox, DAPI, LIP, DROP)

I changed the rnascope_human_tif fn code here from 7 to 4, because 7 did not run at all. 
channels = cellfun(@(x) x{**4**}(1:end-4) , cellfun(@(x) strsplit(x,'_'),{myfiles.name}', 'UniformOutput', false), 'UniformOutput', false); 

**What I got** 
extracted
    {'DAPI'      }
    {'Lipofuscin'}
    {'CH3'       }
    {'CH4'       }

segmented DAPI: 1216 threshold:0.11176
segmented Lipofuscin: 2532 threshold:0.33922
segmented CH3: 1750 threshold:0.49216
segmented CH4: 1200 threshold:0.56667
Completed Masking DAPI
Completed Masking Lipofuscin
Completed Masking CH3
Completed Masking CH4
Started Lipofuscin
Error using cellfun
Input #2 expected to be a cell array, was double instead.

Error in rnascope_human_tif (line 147)
                    dots_m=cellfun(@(x) intersect(x,cel{i}),
                    statsc_m.VoxelIdxList,'UniformOutput',
                    false);

**Comment by madhavitippani** [comment]
Hello,

Sorry for the delayed reply. Can you post your examples images, so that I can reproduce the error and resolve it?

Thanks
Maddy
