### ISSUE TITLE
Under sampling of nuclei 

### ISSUE THREAD

**Issue by krbarbe3** [LieberInstitute/dotdotdot#11]
Currently, I am using the mouse vignette, and the first problem I am having is the correct thresholding of my DAPI signal. I’ve attached the PNG generated from your program of my image. How can I improve the thresholding of DAPI? It is missing the majority of that signal. I know the 488 signal (second column) is poor, but I don’t necessarily need that channel. So far, I have attempted to modify the filter size for thresholding, thresholding, and minN and maxN, but with no success. I’m guessing there is something that needs to change in the threshold settings to improve the signal-to-noise ratio, but I don’t know how to proceed. Any help would be greatly appreciated, and I am really excited about using your software. 
![Test_L6](https://user-images.githubusercontent.com/47804792/126376473-9964fed6-063b-402d-a92a-88011c3fad5d.png)

**Comment by madhavitippani** [comment]
All the settings that can be adjusted for the mouse script (line 60 - 69) are below 

prm.adth.filtrad = 13; 
prm.adth.th = 0.01; 
prm.splitth = 1;
prm.split = 1;
%prm.planewise = 0;
prm.splitplane = round(Z/2);
prm.h=[voxelSizeX,voxelSizeY,voxelSizeZ]; %x,y,z pixel to um 
[cellbw1,~,~,~] = cellsegm.segmct(ch,(0.038),((4/3)*(pi)*(Z/2*0.4)^3),'prm',prm); 
load(fullfile(toolbox,'cellsegm-master','@cellsegm','private','ball3.mat'),'ball')
f= imopen(cellbw1,ball);

I can try calibrating these for your images if you can send me a sample.
