### ISSUE TITLE
Error while running rnascope_mouse - line 159

### ISSUE THREAD

**Issue by vandanashreevs** [LieberInstitute/dotdotdot#12]
Hello, Kindly help me with this. I am getting the same error for my ROIs - has three channels in total (DAPI, FITC and Cy3)

Error using save
Variable 'excel_dots_of_ROI' not found.

Error in rnascope_mouse (line 159)
save([filename(1:end-4),'_dots_of_ROI.mat'],'excel_dots_of_ROI')

**Comment by madhavitippani** [comment]
Did the functions save other outputs like segmentations.mat, img.mat, excel_totaldots.mat?
