### ISSUE TITLE
log4j warnings

### ISSUE THREAD

**Issue by LucasDurieux** [LieberInstitute/dotdotdot#14]
I am new to MatLab and experiencing some issues when trying to run the code. I am trying to run it on the provided data and the following warning shows up:
![image](https://user-images.githubusercontent.com/91056886/133979974-51a8d615-8f3d-4c77-a791-1c6deab12f03.png)

I also run into the following error:
![image](https://user-images.githubusercontent.com/91056886/134019798-e823f761-7182-495c-b93f-d78916401582.png)

Is there a way to fix these issues? My apologies if these questions are naive.

**Comment by madhavitippani** [comment]
Thanks for reaching out, you can ignore the warnings. Which version of matlab are you using. The `regionprops` function is available in versions 2017b or later and also you should have the image processing toolbox pre-installed.
