### ISSUE TITLE
final_table_mouse

### ISSUE THREAD

**Issue by dlhagger** [LieberInstitute/dotdotdot#2]
When running the final mouse table command (screenshot below) - the output files are created but they are blank. Any ideas?

![image](https://user-images.githubusercontent.com/44274286/84796954-3faee280-afc7-11ea-83b5-abda9b6ebc8f.png)

**Comment by andrewejaffe** [comment]
Can you post what solved the issue in case others run into the same issue?

**Comment by dlhagger** [comment]
Sorry! Simple error on my part. - I didn't realize what the path1 string should actually point to. I thought it was where the final .csv files would be placed, but once I corrected to where the .mat files were, everything worked.
