### ISSUE TITLE
"long.csv" and "man.csv" Column Abbreviation Definitions

### ISSUE THREAD

**Issue by jtalboom81** [LieberInstitute/dotdotdot#3]
Dear Dr. Tippani,

Thank you for this fantastic piece of work. You have made my life much more relaxed and will be cited for sure as long as our RNAScope validation works.

With that said, I cannot find where you list what all the .csv column head abbreviations mean! Unless I am mistaken, they appear to be described differently or worded differently across this body of work.

For my example, I have, 
|PO_Cy5 | DO_Cy5 | IO_Cy5 | MI_Cy5 |
| PO_Cy3 | DO_Cy3 | IO_Cy3 | MI_Cy3 | 
|PO_DAPI | DO_DAPI | IO_DAPI | MI_DAPI

Thank you again.

Sincerely,
Josh

**Comment by dlhagger** [comment]
Josh - I'm getting similar outputs - looking at the final_table_mouse.mat file and still a bit confused too. Some clarification would be helpful.

**Comment by jtalboom81** [comment]
> Josh - I'm getting similar outputs - looking at the final_table_mouse.mat file and still a bit confused too. Some clarification would be helpful.

David, like you, I found part of the answer in the author's "final_table_mouse.m" lines 40-44; however, as confirmation of what they are would still be much appreciated.    
```
for ch = 1:numel(channels)
    eval(['PO_',channels{ch},' = sum(excel_totaldots.(channels{ch}).Volume);']);
    eval(['DO_',channels{ch},' = numel(excel_totaldots.(channels{ch}));']);
    eval(['IO_',channels{ch},' = mean(excel_totaldots.(channels{ch}).MeanIntensity);']);
    eval(['MI_',channels{ch},' = mean(img.(channels{ch})(:));']);

**Comment by jtalboom81** [comment]
> Josh - I'm getting similar outputs - looking at the final_table_mouse.mat file and still a bit confused too. Some clarification would be helpful.

Hi dlhagger,

The authors graciously shared with me the following information. Note these data were generated using **rnascopre_mouse.m** followed by **final_table_mouse.m**
 
**man.csv**

**var1**  image name,
**PO_C1** - total C1 pixels in the image
**DO_C1** - total C1 dots in the image
**IO_C1** - Mean Intensity of C1 dots in the image
**MI_C1** - Mean Intensity of the C1 channel in the image

**long_data.csv**

**names** - image name or ROI number in that image (not sure about this)
**Volume** - ROI volume
**P_C1**  - total C1 pixels in that ROI
**MI_P_C1** - Mean intensity of C1 pixels in that ROI
**D_C1** - total C1 dots in that ROI
**V_C1**  - mean volume/size (in pixels) of C1 dots in that ROI
**MI_D_C1** = Mean intensity of C1 dots in that ROI (edited)

Hope this helps.

Best,
Josh

**Comment by andrewejaffe** [comment]
These descriptions have been added to the mouse vignette: https://github.com/LieberInstitute/dotdotdot/blob/master/docs/mouse_vignette.md#description-of-output
