### ISSUE TITLE
Help with downstream analyses when running rnascope_mouse.m

### ISSUE THREAD

**Issue by Sofiemb** [LieberInstitute/dotdotdot#8]
Hi,

I am trying to run the Mouse RNAscope workflow as described in mouse_vignette.md.

I managed to run the entire script and have now the two files: long_data.csv and man.csv but have problems understanding the downstream analyses.

A dataframe from long_data.csv for channel 1 (BdnfEx4) is shown in the guide but I am confused were to find these values in the long_data.csv file.

Is 	no_of_dots_c1 = D_c1 in long_data.csv, and 
	avg_dot_size_c1 = V_c1 in long_data.csv, and
	avg_dot_Intensity_c1 = MI_D_c1 in long_data.csv?

Best regards,

Sofie

**Comment by btrx-ajaffe** [comment]
please see: https://github.com/LieberInstitute/dotdotdot/blob/master/docs/mouse_vignette.md#description-of-output

**Comment by andrewejaffe** [comment]
please see: https://github.com/LieberInstitute/dotdotdot/blob/master/docs/mouse_vignette.md#description-of-output

**Comment by Sofiemb** [comment]
Thanks for the link.

I am just confused how you made this table from the long_data file? I can not find the same values as shown here:

![Udklip](https://user-images.githubusercontent.com/72393726/95209640-e32c3900-07ea-11eb-9faf-5134031cb341.PNG)

Thanks for the help,

Sofie

**Comment by andrewejaffe** [comment]
yeah, that example I guess had old naming...your interpretation in your
original issue is correct

**Comment by Sofiemb** [comment]
Thanks! :)
