### ISSUE TITLE
creating final table when using .tif as an input

### ISSUE THREAD

**Issue by sztankatt** [LieberInstitute/dotdotdot#9]
Hi,

I ran your script using the script on vignette. I have 3 .tif images, 3 channels: DAPI, GFP and TRITC. The files are like this `cropped_WT_20X_00100_CH1.tif`,  `cropped_WT_20X_00100_CH2.tif`,  `cropped_WT_20X_00100_CH3.tif` containing DAPI, GFP, and TRICT in order.

then I run the following code:

    filename` = 'output/cropped_WT_20X_00100'

    toolbox = '~/dotdotdot-master/toolbox'

    addpath(genpath(toolbox))

    DAPI = 'CH1'
    LIP = ''
    DROP = 'Overlay'
    rnascope_human_tif(filename_wt, toolbox, DAPI, LIP, DROP)

sofar, so good. I have the following output files:

- cropped_WT_20X_00100.png
- cropped_WT_20X_00100_dots_of_ROI.mat
- cropped_WT_20X_00100_img.mat
- cropped_WT_20X_00100_segmentation.mat
- cropped_WT_20X_00100_thresholds.mat
- cropped_WT_20X_00100_totaldots.mat

Now, I'd like to create a final table, using the `final_table` function as described.

How do I proceed?

So far I tried the following:

    path1 = 'output'
    ext = 'cropped_WT_20X_00100*.tif'
    toolbox = '~/dotdotdot-master/toolbox'
    channels = {'DAPI', 'CH2', 'CH3'}

    final_table(path1,ext,toolbox,channels)

however this fails... In the vignette ext expect a .czi image, but I have .tif, could that be a problem?

**Comment by sztankatt** [comment]
Ok, it seems that running the `rnascope_human_tif` doesnt create a `excel_totaldots_mask` object....

**Comment by madhavitippani** [comment]
Hello Tamas Sztanka-Toth ,
Sorry for the delayed response, yes the final_table uses the `excel_totaldots_mask` object. But your images don't need lipofuscin masking. You can use the final_table_mouse script to build your final tables.
Thanks
